### ISSUE TITLE
Distinguish message displayed to user when loading marketplace from zero filtered offers

### ISSUE THREAD

**Issue by SamTremko** [vexl-it/vexl#266]
<img width="404" alt="image" src="https://github.com/vexl-it/vexl-next/assets/32439382/a42048f9-62ac-44df-8375-ee8d95992960">

**Comment by kaladivo** [comment]
I'm suggesting a system where we manage the user's experience based on their interactions. If a user has imported their contacts less than an hour ago and has more than 30 connections, we present them with a loading screen, with a countdown to manage expectations. For users with less than 30 connections who aren't seeing anything, we should notify them that they need to expand their network. Similarly, if the user has filters on but doesn't see any corresponding offers in the marketplace, we should explicitly state "No offers for selected filters". If more than an hour has passed since the contacts' import and there are still no offers, we should display "No offers in your network", explaining what it means each time.

This user experience would apply to fresh installations as well, as that's when the user's offers start to get encrypted. We could also consider an additional state when a user has imported less than a set number of contacts (like 10) and doesn't see offers. We should prompt them to import all contacts to see something. Of course, the time intervals and the number of contacts required for activation should be adjustable for optimization.

**Comment by leomira** [comment]
the workflow as you describe it makes sense to me

**Comment by kaladivo** [comment]
AC: 
- **If user has not imported any contacts yet** - display a prompt and button to import contact. "You have not imported any contacts. Import contacts to see offers from you network"
- **If user has imported contacts but have less than 30 (any level) connections** - display a message that their social network is too small and no offers might be displayed. 
- **If user has imported contacts and has more or equal to 30 connections**: 
  - **If 1 hour from the import passed** - show _contact support_ button. Something is wrong.
  - **If user imported the contacts less than 1h ago** - communicate to user that it might take up to an hour to see any offers. `Offers are loading. Offers should be ready for you in X mins`.
- **Do not let user to set filter**, until he gets some offers into state. Hide the button completely - this will eliminate confusion. 
- **If there are offers in state and filter is active but no offers are visible for the current filter** -: `There are no offers that match your filter criteria` with button to _reset filter_
  
Technical insights: 
- add `lastImport` to contacts state (MMKV atom) to hold value when last import occurred. Make sure to set it when contacts are successfully imported.
- Make all values as constants (time, number of connections) so we can change them based on product discovery.

**Comment by prusnak** [comment]
Good writeup! ACK

> has more or equal to 30 connections

Is 30 enough? I am not sure what's your experience but maybe 50 or even 100 is more appropriate for the cut-off?

**Comment by leomira** [comment]
Really well written up! 
My comment: 
1. agreed with @prusnak , 30 might be too little
2. let's sync on the design we will use and when. We have kick ass screens ready utilizing our fluent device, this is the best place to start using it properly.

**Comment by leomira** [comment]
I tested this and it seems to be working well!
