### ISSUE TITLE
Add full text search above offers

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#290]
Implement full text search in Filter, which search over:

- description
- common friends and their phone numbers
- location strings
- own comments or tags (after this is implemented)

**Comment by kaladivo** [comment]
To be changed: 
1. add search text input into marketplace screen (next to filter button)
2. Add filter functionality to marketplace list
3. Recent searches functionality

Questions: 
1. How should we sort the results? - use some library for example [this](https://www.npmjs.com/package/lunr)
2. Should we highlight matches in text? - library should give us some results. If this is too complicated omit this in first version.
3. Is filter highlight enough to let user know that the filter is on? - text input is next to the filter button. It will be highlighted once search text filter is set. This should be enought to let user know that the filter is 
4. Should we change no results found text / action button, to remove text filter?
5. Is filter applied when searching with text? **yes**
6. there are some doubts about what properties of the offers should be searched? - see 
7. When there are multiple words in search use and instead of or
