### ISSUE TITLE
Add filtering by number of common friends

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#291]
In Filter dialog, it should be possible to filter by first-degree offers or numbers of common friends, so user can easily filter out less trusted offers.

**Comment by leomira** [comment]
as described here, this was delivered in Vexl 2.0
we might consider filtering according to a number of common friends, i.e. - I only want to see offer with at least 3 and more common friends.

**Comment by kaladivo** [comment]
Currently, the number of common friends needed to make the offer visible is **1**. I would argue to either: 

- Create new discussion issue to decide what the system of filtering should be (should we increase the number, should we indroduce another property to filter the offers by?)
- Create new issue for increasing the number

**Comment by kaladivo** [comment]
1. First degree offer is always visible regardless of common friends (done here: #340).
2. Communicate what first degree means when there are no common friends but offer is 1st degree.

**Comment by leomira** [comment]
We have the information popup already designed (attached here), I would reuse it in the request dialogue. 

I suggest this wording: 
"What does this mean?" + button "Check it out" or "Learn more"

On the popup that follows we should communicate:

**situation no1 - you are a direct friend with 0 common friends**
headline: Offer from a direct friend
You see this offer because the counterparty has your phone number saved in their contact list. Be cautious, we cannot verify if you really know each other in the real life. 

**situation no2 - you are a direct friend with XY common friends**
headline: Offer from a direct friend
You see this offer because the counterparty has your phone number saved in their contact list. Don't forget to verify their identity with a common contact.

**situation no3 - you are a 2nd degree friend with XY common friends**
This is a contact with whom you have no direct connection. Don't forget to verify their identity with a common contact.

I think it would be best to always show the popup according to the state of the request rather than show one long dialogue explaining all three. 
<img width="315" alt="Snímka obrazovky 2023-06-21 o 11 17 15" src="https://github.com/vexl-it/vexl/assets/25779015/1a8debcf-83b7-4e85-b42a-3053ca8ecc89">

**Comment by leomira** [comment]
moved the discussion to #341 , this was originally a different issue, just the conversation derailed a bit.

**Comment by leomira** [comment]
We added an option to sort offers according to the number of connections which is a good substitute for the proposed filter. I am closing this for now.
