### ISSUE TITLE
Add contact via chat

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#323]
Having #282 implemented opened the door for even better support of the growth of the social network.

One of such things would be an option to have a button for adding a phone number directly after reveal identity. 
The workflow could be similar to reveal identity itself: you could prompt the couterparty to reveal your whole number and once he agrees, after symmetrical reveal user would be prompted to save it directly to the app and the phone. 

connected to #314

**Comment by leomira** [comment]
connected to #283 a #300

**Comment by kaladivo** [comment]
To be specified in order to create implementation plan: 

**See Figma flow, questions are resolved there.**

There should be option to change user name with default value of name of user set in onboarding
Add checkbox to allow user to add this contact into phone contacts

How should we handle the groups? **We should add contact imported this way to Vexl group in contact list.** 
Should there be checkbox wether to contact to Vexl group. **yes, there should be two checkboxes. Two checkboxes should be on the screen.**

1. Flow of this functionality for example
  - User asks for contact reveal
  - Other side gets prompt to reveal his phone number
  - If revealed, both users see button to add each other to contact (phone number with real user names specified in onboarding)
 2. Should we go with design from designer or is it ok to try to implement this without design?

**Comment by leomira** [comment]
design: https://www.figma.com/file/UzjHcXPfNOOTVmcafQx4iP/Vexl-playground?type=design&node-id=0%3A1&mode=design&t=omWq2fDb4gmc5yjL-1

**Comment by leomira** [comment]
let's not forget upgrading the menu icon for the chat

**Comment by leomira** [comment]
seems to be working well!
